# Site settings
title: "Bits Of Berlin"
description: "This is a podcast about tech in Berlin"
baseurl: ""
url: "http://bitsofberlin.github.io"
username: bitsofberlin

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
- jemoji

