# Site settings
title: "TODO: Make a Podcast"
description: "This is a podcast about tech in Berlin"
baseurl: ""
url: "http://todocastberlin.github.io"
username: todocastberlin

permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

gems:
- jekyll-sitemap
- jemoji

