# Site settings
title: "bits of berlin"
description: "This is a podcast about tech in Berlin."
baseurl: ""
url: "https://bitsofberlin.org"
username: bitsofberlin

emoji_dir: /css/emoji
permalink: /:year/:month/:day/:title/

category_title_prefix: ''
category_dir: ''

# Build settings
markdown: kramdown

plugins:
- jekyll-sitemap
- jemoji
- jekyll-redirect-from
